site_name: The Midnight Wiki
docs_dir: 'docs'
side_dir: 'site'
theme:
    name: null
    custom_dir: 'cinder'
markdown_extensions:
    - admonition

nav:
    - Home: index.md
    - Credits: credits.md