site_name: The Midnight Wiki
docs_dir: 'docs'
site_dir: 'site'

theme: readthedocs

markdown_extensions:
    - admonition

nav:
    - Home: index.md
    - Rewrite Information: rewrite.md
    - About:
        - What is The Midnight?: about.md
        - Contributing to the Wiki: about/contribution.md
        - Credits: about/credits.md